// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxDacerUmWPlFOrSx_O6fuqKhHHS3BjA',
    appId: '1:19970510580:web:fdeb9b7ba79709ee6158a1',
    messagingSenderId: '19970510580',
    projectId: 'my-deep-notes',
    authDomain: 'my-deep-notes.firebaseapp.com',
    storageBucket: 'my-deep-notes.appspot.com',
    measurementId: 'G-ZC1VHC75FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrsGLPro90DP8j2CPSI2EQXKA-5j208k',
    appId: '1:19970510580:android:74fddcc4e2f377af6158a1',
    messagingSenderId: '19970510580',
    projectId: 'my-deep-notes',
    storageBucket: 'my-deep-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_L10cjlgWUaHCtye5mZq3GfiyY2PL2Q',
    appId: '1:19970510580:ios:98e74660259dfced6158a1',
    messagingSenderId: '19970510580',
    projectId: 'my-deep-notes',
    storageBucket: 'my-deep-notes.appspot.com',
    iosClientId: '19970510580-hl21cu2rd24u48s0pnpj7h4ih3el4908.apps.googleusercontent.com',
    iosBundleId: 'com.deepthings.deepnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI_L10cjlgWUaHCtye5mZq3GfiyY2PL2Q',
    appId: '1:19970510580:ios:e469e87db87a4a4c6158a1',
    messagingSenderId: '19970510580',
    projectId: 'my-deep-notes',
    storageBucket: 'my-deep-notes.appspot.com',
    iosClientId: '19970510580-8ick6pak4sqkku8cqmk6a87btf9ca4te.apps.googleusercontent.com',
    iosBundleId: 'com.deepthings.deepnotes.RunnerTests',
  );
}
